// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mpp_session_mvx
    (
        init => init
        upgrade => upgrade
        open => open
        top_up => top_up
        settle => settle
        close => close
        request_close => request_close
        getSession => sessions
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
