// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct MppSessionContractProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for MppSessionContractProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = MppSessionContractProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        MppSessionContractProxyMethods { wrapped_tx: tx }
    }
}

pub struct MppSessionContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> MppSessionContractProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> MppSessionContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> MppSessionContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    /// Open a new payment session. 
    /// Locks the payment sent in the transaction. 
    pub fn open<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        receiver: Arg0,
        deadline: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ManagedBuffer<Env::Api>> {
        self.wrapped_tx
            .raw_call("open")
            .argument(&receiver)
            .argument(&deadline)
            .original_result()
    }

    pub fn top_up<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        channel_id: Arg0,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("top_up")
            .argument(&channel_id)
            .original_result()
    }

    pub fn settle<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<BigUint<Env::Api>>,
        Arg2: ProxyArg<u64>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        channel_id: Arg0,
        amount: Arg1,
        nonce: Arg2,
        signature: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("settle")
            .argument(&channel_id)
            .argument(&amount)
            .argument(&nonce)
            .argument(&signature)
            .original_result()
    }

    pub fn close<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<BigUint<Env::Api>>,
        Arg2: ProxyArg<u64>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        channel_id: Arg0,
        amount: Arg1,
        nonce: Arg2,
        signature: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("close")
            .argument(&channel_id)
            .argument(&amount)
            .argument(&nonce)
            .argument(&signature)
            .original_result()
    }

    pub fn request_close<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        channel_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("request_close")
            .argument(&channel_id)
            .original_result()
    }

    pub fn sessions<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        channel_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, SessionData<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getSession")
            .argument(&channel_id)
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone, Debug)]
pub struct SessionData<Api>
where
    Api: ManagedTypeApi,
{
    pub employer: ManagedAddress<Api>,
    pub receiver: ManagedAddress<Api>,
    pub token_identifier: EgldOrEsdtTokenIdentifier<Api>,
    pub amount_locked: BigUint<Api>,
    pub amount_settled: BigUint<Api>,
    pub nonce: u64,
    pub deadline: u64,
    pub status: u8,
}
